### ISSUE TITLE
false update

### ISSUE THREAD

**Issue by Sadi58** [Ultimate-Hosts-Blacklist/adblock-nocoin-list#1]
Whenever [hostsblock](https://github.com/Sadi58/hostsblock) checks https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt somehow it detects update although hosts.txt file there hasn't changed. Any ideas?

**Comment by funilrys** [comment]
May I ask how `it detects update although hosts.txt` ?

**Comment by Sadi58** [comment]
I don't know frankly, I didn't look because the hostsblock script is written by someone else, and I simply wrote a sort of GUI script for it.
I guess it looks at the file timestamp.

**Comment by funilrys** [comment]
According to https://github.com/hoshsadiq/adblock-nocoin-list/commits/master/hosts.txt the last update was 2 days ago so unless you cache your file, you already got it or GitHub has a bug it's kinda strange what you ask here ...

___
Okay so HASH is way better than timestamp in my opinion ... I think you should ask upstream as you forked it..

**Comment by Sadi58** [comment]
OK, thanks. It seems either Github has a sort of bug and/or hostsblock should use something else to check for updates.

**Comment by funilrys** [comment]
Also, you should add @hoshsadiq to the loop at this is the repository used to clean his list before we add it to https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist.

The upstream repository is https://github.com/hoshsadiq/adblock-nocoin-list.
